// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteGOL.Infrastructing.Data.Context;

namespace TesteGOL.Infrastructing.Data.Migrations
{
    [DbContext(typeof(GolContext))]
    partial class GolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteGOL.Domain.Cadastros.Entidades.Airplane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodigoAviao")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("DataRegistro");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Passageiros");

                    b.HasKey("Id");

                    b.ToTable("Airplane");
                });
#pragma warning restore 612, 618
        }
    }
}
