//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using TesteGOL.Domain.Cadastros.Entidades;

namespace TesteGOL.Application.Cadastros.ViewModels
{
   

    public partial class AirplaneViewModel
    {
        public string CodigoAviao { get; set; }
        public string Modelo { get; set; }
        public int Passageiros { get; set; }
        public DateTime DataRegistro { get; set; }

        internal Airplane ToModel()
        {
            return new Airplane(CodigoAviao, Modelo, Passageiros, DataRegistro);
        }
    }
}
